import type { Metadata } from "next";
import { Noto_Sans_KR, Noto_Sans_Mono } from "next/font/google";
import "@/styles/globals.css";
import SideNavigation from "@/components/common/navigation/SideNavigation";
// shadcn UI
import { ToastAction } from "@/components/ui/toast"

const geistSans = Noto_Sans_KR({
  variable: "--font-Noto-Sans-KR",
  subsets: ["latin"],
});

const geistMono = Noto_Sans_Mono({
  variable: "--font_Noto_Sans_Mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shade Board App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SideNavigation />
        {children}
        <ToastAction altText={"aa"} />
      </body>
    </html>
  );
}
